source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "redis"

# 認証
gem "devise"
gem "devise_invitable", "~> 2.0"
gem "devise-two-factor"
gem "devise-pwned_password"
gem "omniauth-google-oauth2"

gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

# 認可
gem "pundit"
gem "bcrypt", "~> 3.1.7"

# 決済
gem "stripe", ">= 8.0"

# i18n
gem "rails-i18n"
gem "devise-i18n"

# その他
gem "geocoder"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "letter_opener_web", "~> 3.0"
end

group :test do
  gem "capybara"
  gem "simplecov", require: false
end
